services:
    canonknipser.IMThumbnailer.listener:
        class: canonknipser\IMThumbnailer\event\main_listener
        arguments:
            - '@config'
        tags:
            - { name: event.listener }
