services:
    canonknipser.imthumbnailer.listener:
        class: canonknipser\imthumbnailer\event\main_listener
        arguments:
            - '@config'
            - '@request'
            - 'log'
        tags:
            - { name: event.listener }
            
            